Repository ebrickdev/ebrick, pull requests merged in 2024-09, with the labels that each got.

#19 change subject param in interface message to topic to common term
  messaging/messaging.go
Labels: enhancement, chore

#20 Add subject to message publishing interface
  messaging/messaging.go
  messaging/nats.go
Labels: enhancement

#22 bootstrap OIDC when start application
  server/options.go
  web/middleware/oidc_middleware.go
Labels: enhancement

#21 Feature/18 support redis streams
  messaging/consumer_config.go
  messaging/messaging.go
  messaging/nats.go
  messaging/redis_stream.go
Labels: enhancement, feat

#23 Refactor messaging configuration loading and initialization
  config/config.go
  ebrick.go
  messaging/config.go
  messaging/go.mod
  messaging/go.sum
  messaging/messaging.go
  messaging/options.go
  messaging/redis_stream.go
  module/options.go
  options.go
Labels: enhancement

#24 Refactor cache configuration loading and initialization
  cache/cache.go
  cache/go.mod
  cache/go.sum
  ebrick.go
  go.mod
  go.sum
  module/options.go
  options.go
Labels: enhancement
